### ISSUE TITLE
Stuck at "Synchronizing"

### ISSUE THREAD

**Issue by thealphonso** [Privatix/dapp-gui#102]
![screenshot from 2018-07-03 15-56-26](https://user-images.githubusercontent.com/22868370/42272596-52b5363c-7f8f-11e8-991a-a4e8abf2afe0.png)
Done all the steps to install and run the alpha 0.7.0. Stuck at the last one, just prior to enable a new VPN connection.
Stuck at synchronizing, probably because the server is offline or unavailable anymore. Cannot cancel and chose another VPN service

**Comment by drew2a** [comment]
The issue was solved in 0.7.1 release.
