### ISSUE TITLE
'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by R00iBaard** [Privatix/dapp-gui#23]
Building the application via OSX works fine, building from Windows :

C:\Users\ABCD\Privatix\dapp-gui>npm run build

> GUI@0.1.0 build C:\Users\ABCD\Privatix\dapp-gui
> rm -rf ./build && mkdir ./build && tslint -c ./configs/tslint.json -p ./configs/tsconfig.json && webpack --mode development --config configs/webpack.config.js && cp -R assets/* ./build/

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GUI@0.1.0 build: `rm -rf ./build && mkdir ./build && tslint -c ./configs/tslint.json -p ./configs/tsconfig.json && webpack --mode development --config configs/webpack.config.js && cp -R assets/* ./build/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GUI@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ABCD\AppData\Roaming\npm-cache\_logs\2018-05-09T19_50_18_524Z-debug.log

**Comment by drew2a** [comment]
Hey, @R00iBaard!

First of all, thank you for your interest in this project. 

On this stage of developing, we don't support Windows as target OS.

But, you can add `windows build` by yourself: [how to contribute to Privatix](https://github.com/Privatix/dapp-gui/blob/master/CONTRIBUTING.md#did-you-write-a-patch-that-fixes-a-bug)

**Comment by drew2a** [comment]
@R00iBaard,  issue has fixed.
